// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using techtest2.Models;

namespace techtest2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200218121454_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("techtest2.Models.Language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("langName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("languages");

                    b.HasData(
                        new { id = 1, langName = "English" },
                        new { id = 2, langName = "Chineese" },
                        new { id = 3, langName = "Thai" },
                        new { id = 4, langName = "Tamil" },
                        new { id = 5, langName = "korean" },
                        new { id = 6, langName = "burmese" }
                    );
                });

            modelBuilder.Entity("techtest2.Models.Level", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("levelName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("tradeId");

                    b.HasKey("id");

                    b.ToTable("levels");

                    b.HasData(
                        new { id = 1, levelName = "HIGH", tradeId = 1 },
                        new { id = 2, levelName = "MEDIUM", tradeId = 2 },
                        new { id = 3, levelName = "LOW", tradeId = 1 }
                    );
                });

            modelBuilder.Entity("techtest2.Models.Trade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tradeName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("trades");

                    b.HasData(
                        new { id = 1, tradeName = "MS INTERNATIONAL" },
                        new { id = 2, tradeName = "RAHIM INTERNATIONAL" }
                    );
                });

            modelBuilder.Entity("techtest2.Models.TradingInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("active");

                    b.Property<string>("developmentOfficer")
                        .IsRequired();

                    b.Property<string>("language")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("levelName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("manager")
                        .IsRequired();

                    b.Property<string>("syllabus")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("syllabusFileName");

                    b.Property<string>("testPlanFileName");

                    b.Property<string>("tradeName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("tradingInfoes");
                });
#pragma warning restore 612, 618
        }
    }
}
